### ISSUE TITLE
Set "System Default" theme by default

### ISSUE THREAD

**Issue by xmha97** [massivemadness/Squircle-CE#171]
Please set the system default theme by default.
![Screenshot_2023-03-10-20-55-41-046_com.vincentengelsoftware.vesandroidimagecompare.jpg](https://user-images.githubusercontent.com/23485114/224383215-6caa3268-c0e8-4bad-8640-f67fdfecfa78.jpg)

**Comment by massivemadness** [comment]
This setting is available only for Android 10 or higher. If the default value is set to "System default", the light theme will be used for older OS versions instead of the dark theme, which doesn't seem right. Although this setting can be ported to previous versions of Android, they will always use the light theme for the splash screen, despite the fact that the dark theme is selected in the settings.

**Comment by xmha97** [comment]
You can set "System Default" as default if Android is more than 10.
