### ISSUE TITLE
Separation of project into group of projects

### ISSUE THREAD

**Issue by MadRatSRP** [massivemadness/Squircle-CE#88]
Hi and thank you for such an interesting project! I wanted to refactor some code, mostly dependencies, and when i forked your project it took 15 minutes on my device to compile and run on my device. Thats a lot, you know :D I didnt look into your code but the simplest solution that comes to mind is separation of this project into group of projects. For example, you might have 1 project for ide code and 1 project for languages module code (i mean as a different repositories), so we could have languages jars in an ide project as a gradle dependencies.

**Comment by massivemadness** [comment]
Hi @MadRatSRP, I don't think I need faster cold builds (at least right now). The cold build is always so long because the project contains 30+ modules, and it takes for me around 6 mins or so. After the first cold build, gradle caches most of the project modules, so the hot build will only take 2-3 mins.
